---
- name: install PHP7 packages
  apt: name={{ item }} state=present
  with_items:
    - php7.0-fpm
    - php7.0-cli
    - php7.0-curl
    - php7.0-dev
    - php7.0-pgsql
    - php-redis
    - php7.0-mbstring

- name: Install composer
  include: ./composer.yml
