---
- name: Install node.js packages
  apt: name={{ item }} state=present
  with_items:
    - nodejs
    - npm

- name: Install latest node.js process manager
  npm: name=n global=yes

- name: Enable latest Node.js
  command: n stable

- name: Install pm2 process manager
  npm: name=pm2 global=yes

- name: Install bower
  npm: name=bower global=yes